//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available AddIns.
        /// </summary>
        internal static string AvailableAddIns {
            get {
                return ResourceManager.GetString("AvailableAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available:.
        /// </summary>
        internal static string AvailableTxt {
            get {
                return ResourceManager.GetString("AvailableTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Updates.
        /// </summary>
        internal static string AvailableUpdatesTxt {
            get {
                return ResourceManager.GetString("AvailableUpdatesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string CancelHelp {
            get {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTxt {
            get {
                return ResourceManager.GetString("CancelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string ClosesTheDialogBoxWithoutSavingAnyChangesYouHaveMade {
            get {
                return ResourceManager.GetString("ClosesTheDialogBoxWithoutSavingAnyChangesYouHaveMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyTxt {
            get {
                return ResourceManager.GetString("CopyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding protocols..
        /// </summary>
        internal static string FindingProtocols {
            get {
                return ResourceManager.GetString("FindingProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed:.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        internal static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies files to the clipboard..
        /// </summary>
        internal static string LibraryCopyHelp {
            get {
                return ResourceManager.GetString("LibraryCopyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows product and library versions..
        /// </summary>
        internal static string LibraryListHelp {
            get {
                return ResourceManager.GetString("LibraryListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Versions.
        /// </summary>
        internal static string LibraryVersionsTxt {
            get {
                return ResourceManager.GetString("LibraryVersionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationTxt {
            get {
                return ResourceManager.GetString("LocationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameTxt {
            get {
                return ResourceManager.GetString("NameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 3.5.
        /// </summary>
        internal static string NETFramework35 {
            get {
                return ResourceManager.GetString("NETFramework35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net framework 3.5 SP1 must be installed before the application can be used..
        /// </summary>
        internal static string NetFramework35SP1MustBeInstalledBeforeTheApplicationCanBeUsed {
            get {
                return ResourceManager.GetString("NetFramework35SP1MustBeInstalledBeforeTheApplicationCanBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net framework 3.5 SP1 or 4.0 must be installed before the application can be used..
        /// </summary>
        internal static string NetFramework35SP1Or40MustBeInstalledBeforeTheApplicationCanBeUsed {
            get {
                return ResourceManager.GetString("NetFramework35SP1Or40MustBeInstalledBeforeTheApplicationCanBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.0.
        /// </summary>
        internal static string NETFramework40 {
            get {
                return ResourceManager.GetString("NETFramework40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates available.
        /// </summary>
        internal static string NewProtocolsAvailableTxt {
            get {
                return ResourceManager.GetString("NewProtocolsAvailableTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new updates available. Do you want to download them?.
        /// </summary>
        internal static string NewProtocolsDownloadTxt {
            get {
                return ResourceManager.GetString("NewProtocolsDownloadTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not hex string.
        /// </summary>
        internal static string NotHexString {
            get {
                return ResourceManager.GetString("NotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        internal static string ProtocolsTxt {
            get {
                return ResourceManager.GetString("ProtocolsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SP .
        /// </summary>
        internal static string SP {
            get {
                return ResourceManager.GetString("SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type .
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionTxt {
            get {
                return ResourceManager.GetString("VersionTxt", resourceCulture);
            }
        }
    }
}
