//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DLMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.DLMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports scope of access violated..
        /// </summary>
        internal static string AccessViolatedTxt {
            get {
                return ResourceManager.GetString("AccessViolatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Data Block Number Invalid..
        /// </summary>
        internal static string DataBlockNumberInvalidTxt {
            get {
                return ResourceManager.GetString("DataBlockNumberInvalidTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Data Block Unavailable..
        /// </summary>
        internal static string DataBlockUnavailableTxt {
            get {
                return ResourceManager.GetString("DataBlockUnavailableTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect mode..
        /// </summary>
        internal static string DisconnectMode {
            get {
                return ResourceManager.GetString("DisconnectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a hardware fault..
        /// </summary>
        internal static string HardwareFaultTxt {
            get {
                return ResourceManager.GetString("HardwareFaultTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a inconsistent Class or object..
        /// </summary>
        internal static string InconsistentClassTxt {
            get {
                return ResourceManager.GetString("InconsistentClassTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # IC | OBIS | VERSION | DESCRIPTION | UI Type
        ///1;0.0.0.1.0.255;0;Cum. Billing Count
        ///1;0.0.0.1.1.255;0;Available Billing Periods
        ///1;0.0.42.0.0.255;0;COSEM Logical Device Name;10
        ///1;0.0.43.1.1.255;0;Invocation Counter #1 (PC)
        ///1;0.0.43.1.2.255;0;Invocation Counter #2 (MR)
        ///1;0.0.43.1.3.255;0;Invocation Counter #3 (US)
        ///1;0.0.43.1.4.255;0;Invocation Counter #4 (Push)
        ///1;0.0.43.1.5.255;0;Invocation Counter #5 (FW)
        ///1;0.0.43.1.6.255;0;Invocation Counter #6 (IHD)
        ///1;0.0.94.91.0.255;0;Cumulative Tamper Count
        ///1;0.0.94.91.9. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key usage. .
        /// </summary>
        internal static string InvalidKeyUsage {
            get {
                return ResourceManager.GetString("InvalidKeyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Logical name..
        /// </summary>
        internal static string InvalidLogicalName {
            get {
                return ResourceManager.GetString("InvalidLogicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security suite version..
        /// </summary>
        internal static string InvalidSecuritySuiteVersion {
            get {
                return ResourceManager.GetString("InvalidSecuritySuiteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;0.0.96.1.0.255;0;Manufacturing number
        ///1;0.0.96.1.10.255;0;Metering Point Identifier
        ///1;0.0.96.1.3.255;0;Equipment Class Identifier
        ///1;0.0.96.1.5.255;0;UNI/TS Reference version
        ///17;0.0.41.0.0.255;0;SAP assigment
        ///1;0.0.42.0.0.255;0;Logical Device Name
        ///15;0.0.40.0.1.255;2;Management Association
        ///15;0.0.40.0.16.255;2;Public Association
        ///15;0.0.40.0.3.255;2;Installer/Maintainer Association
        ///15;0.0.40.0.48.255;2;Guarantor Authority Association
        ///15;0.0.40.0.64.255;2;Gateway Association
        ///15;0.0.40.0.32.255;2;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Name.
        /// </summary>
        internal static string LogicalNameTxt {
            get {
                return ResourceManager.GetString("LogicalNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Long Get Or Read Aborted..
        /// </summary>
        internal static string LongGetOrReadAbortedTxt {
            get {
                return ResourceManager.GetString("LongGetOrReadAbortedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Long Set Or Write Aborted..
        /// </summary>
        internal static string LongSetOrWriteAbortedTxt {
            get {
                return ResourceManager.GetString("LongSetOrWriteAbortedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : No Long Get Or Read In Progress..
        /// </summary>
        internal static string NoLongGetOrReadInProgressTxt {
            get {
                return ResourceManager.GetString("NoLongGetOrReadInProgressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : No Long Set Or Write In Progress..
        /// </summary>
        internal static string NoLongSetOrWriteInProgressTxt {
            get {
                return ResourceManager.GetString("NoLongSetOrWriteInProgressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0-64.0.1.0.0-99,255;1,3,4;6,17,18;Ch. $B;Billing period counter (1);;;#$F
        ///0.0-64.0.1.1.255;1,3,4;6,17,18;Ch. $B;No. of available billing periods (1);;;
        ///0.0-64.0.1.2.0-99;1,3,4;6,9,21,25;Ch. $B;Time stamp of the billing period (1);;;#$F
        ///0.0-64.0.1.2.255;1,3,4;6,9,21,25;Ch. $B;Time stamp of the most recent billing period (1) closed;;;
        ///0.0-64.0.1.3.0-99,255;1,3,4;6,17,18;Ch. $B;Billing period counter (2), VZ;;;#$F
        ///0.0-64.0.1.4.255;1,3,4;6,17,18;Ch. $B;No. of available billing periods (2);;;
        ///0.0-64.0.1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OBISCodes {
            get {
                return ResourceManager.GetString("OBISCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Other Reason..
        /// </summary>
        internal static string OtherReasonTxt {
            get {
                return ResourceManager.GetString("OtherReasonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports Read-Write denied..
        /// </summary>
        internal static string ReadWriteDeniedTxt {
            get {
                return ResourceManager.GetString("ReadWriteDeniedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDLC message rejected..
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;0.1.94.96.2.255;0;Storage Device Failure Date/Time
        ///1;0.1.94.96.22.255;0;LCD time-to-return to default screen
        ///1;0.1.94.96.23.255;0;LCD auto scroll time
        ///1;0.1.94.96.24.255;0;LCD night off option
        ///1;0.1.94.96.25.255;0;Start-stop time setting of LCD night off
        ///9;0.1.94.96.10.255;0;Meter Program Configuration
        ///9;0.1.94.96.11.255;0;Meter Program Configuration Status
        ///1;0.96.94.96.8.255;0;Remote output relay control Selection of the input control signals
        ///1;0.96.94.96.9.255;0;Auto recovery operation times of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaudiArabia {
            get {
                return ResourceManager.GetString("SaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # IC | OBIS | VERSION | DESCRIPTION | UI Type
        ///3;1.1.94.34.1.255;0;Clock Time Shift Invalid Limit
        ///3;0.1.94.34.1.255;0;Active Demand Control Threshold Rate 1 Contract 1
        ///3;0.1.94.34.2.255;0;Active Demand Control Threshold Rate 2 Contract 1
        ///3;0.1.94.34.3.255;0;Active Demand Control Threshold Rate 3 Contract 1
        ///3;0.1.94.34.4.255;0;Active Demand Control Threshold Rate 4 Contract 1
        ///3;0.1.94.34.21.255;0;Active Demand Control Threshold Rate 1 Contract 3
        ///3;0.1.94.34.22.255;0;Active Demand Control Threshold Rate 2 Cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a temporary failure..
        /// </summary>
        internal static string TemporaryFailureTxt {
            get {
                return ResourceManager.GetString("TemporaryFailureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacceptable frame..
        /// </summary>
        internal static string UnacceptableFrame {
            get {
                return ResourceManager.GetString("UnacceptableFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unavailable object..
        /// </summary>
        internal static string UnavailableObjectTxt {
            get {
                return ResourceManager.GetString("UnavailableObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a undefined object..
        /// </summary>
        internal static string UndefinedObjectTxt {
            get {
                return ResourceManager.GetString("UndefinedObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A260*60s.
        /// </summary>
        internal static string UnitA260Txt {
            get {
                return ResourceManager.GetString("UnitA260Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active energy W*60*60s.
        /// </summary>
        internal static string UnitActiveEnergyTxt {
            get {
                return ResourceManager.GetString("UnitActiveEnergyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power P watt W = J/s.
        /// </summary>
        internal static string UnitActivePowerTxt {
            get {
                return ResourceManager.GetString("UnitActivePowerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active energy meter constant 1/Wh.
        /// </summary>
        internal static string UnitActiveTxt {
            get {
                return ResourceManager.GetString("UnitActiveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent energy VA*60*60s.
        /// </summary>
        internal static string UnitApparentEnergyTxt {
            get {
                return ResourceManager.GetString("UnitApparentEnergyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power S.
        /// </summary>
        internal static string UnitApparentPowerTxt {
            get {
                return ResourceManager.GetString("UnitApparentPowerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent energy meter constant.
        /// </summary>
        internal static string UnitApparentTxt {
            get {
                return ResourceManager.GetString("UnitApparentTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity C farad C/V = As/V.
        /// </summary>
        internal static string UnitCapacityTxt {
            get {
                return ResourceManager.GetString("UnitCapacityTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductance siemens 1/ohm.
        /// </summary>
        internal static string UnitConductanceTxt {
            get {
                return ResourceManager.GetString("UnitConductanceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected volume flux m3/60*60s.
        /// </summary>
        internal static string UnitCorrectedVolumeFluxHourTxt {
            get {
                return ResourceManager.GetString("UnitCorrectedVolumeFluxHourTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected volume m3.
        /// </summary>
        internal static string UnitCorrectedVolumeTxt {
            get {
                return ResourceManager.GetString("UnitCorrectedVolumeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected volume flux m3/24*60*60s.
        /// </summary>
        internal static string UnitCorrecteVolumeFluxDayTxt {
            get {
                return ResourceManager.GetString("UnitCorrecteVolumeFluxDayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current I ampere A.
        /// </summary>
        internal static string UnitCurrentTxt {
            get {
                return ResourceManager.GetString("UnitCurrentTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string UnitDayTxt {
            get {
                return ResourceManager.GetString("UnitDayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical charge Q coulomb C = As.
        /// </summary>
        internal static string UnitElectricalChargeTxt {
            get {
                return ResourceManager.GetString("UnitElectricalChargeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical field strength E V/m.
        /// </summary>
        internal static string UnitElectricalFieldStrengthTxt {
            get {
                return ResourceManager.GetString("UnitElectricalFieldStrengthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy joule J = Nm = Ws.
        /// </summary>
        internal static string UnitEnergyJouleTxt {
            get {
                return ResourceManager.GetString("UnitEnergyJouleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy newtonmeter J = Nm = Ws.
        /// </summary>
        internal static string UnitEnergyTxt {
            get {
                return ResourceManager.GetString("UnitEnergyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force F newton N.
        /// </summary>
        internal static string UnitForceTxt {
            get {
                return ResourceManager.GetString("UnitForceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency f.
        /// </summary>
        internal static string UnitFrequencyTxt {
            get {
                return ResourceManager.GetString("UnitFrequencyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string UnitHourTxt {
            get {
                return ResourceManager.GetString("UnitHourTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induction T tesla Wb/m2.
        /// </summary>
        internal static string UnitInductionTxt {
            get {
                return ResourceManager.GetString("UnitInductionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inductivity L henry H = Wb/A.
        /// </summary>
        internal static string UnitInductivityTxt {
            get {
                return ResourceManager.GetString("UnitInductivityTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length l meter m.
        /// </summary>
        internal static string UnitLengthTxt {
            get {
                return ResourceManager.GetString("UnitLengthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local currency.
        /// </summary>
        internal static string UnitLocalCurrencyTxt {
            get {
                return ResourceManager.GetString("UnitLocalCurrencyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic flux F weber Wb = Vs.
        /// </summary>
        internal static string UnitMagneticFluxTxt {
            get {
                return ResourceManager.GetString("UnitMagneticFluxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic field strength H A/m.
        /// </summary>
        internal static string UnitMagneticTxt {
            get {
                return ResourceManager.GetString("UnitMagneticTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass flux kg/s.
        /// </summary>
        internal static string UnitMassKgPerSecondTxt {
            get {
                return ResourceManager.GetString("UnitMassKgPerSecondTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass m kilogram kg.
        /// </summary>
        internal static string UnitMassKgTxt {
            get {
                return ResourceManager.GetString("UnitMassKgTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string UnitMinuteTxt {
            get {
                return ResourceManager.GetString("UnitMinuteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string UnitMonthTxt {
            get {
                return ResourceManager.GetString("UnitMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Unit.
        /// </summary>
        internal static string UnitNoneTxt {
            get {
                return ResourceManager.GetString("UnitNoneTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Unit.
        /// </summary>
        internal static string UnitOtherTxt {
            get {
                return ResourceManager.GetString("UnitOtherTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase angle degree rad*180/p.
        /// </summary>
        internal static string UnitPhasAngleDegreeTxt {
            get {
                return ResourceManager.GetString("UnitPhasAngleDegreeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure p bar 10-5 N/m2.
        /// </summary>
        internal static string UnitPressureBarTxt {
            get {
                return ResourceManager.GetString("UnitPressureBarTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure p pascal N/m2.
        /// </summary>
        internal static string UnitPressurePascalTxt {
            get {
                return ResourceManager.GetString("UnitPressurePascalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive energy var*60*60s.
        /// </summary>
        internal static string UnitReactiveEnergyTxt {
            get {
                return ResourceManager.GetString("UnitReactiveEnergyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive power Q.
        /// </summary>
        internal static string UnitReactivePowerTxt {
            get {
                return ResourceManager.GetString("UnitReactivePowerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive energy meter constant.
        /// </summary>
        internal static string UnitReactiveTxt {
            get {
                return ResourceManager.GetString("UnitReactiveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance R ohm = V/A.
        /// </summary>
        internal static string UnitResistanceTxt {
            get {
                return ResourceManager.GetString("UnitResistanceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistivity.
        /// </summary>
        internal static string UnitResistivityTxt {
            get {
                return ResourceManager.GetString("UnitResistivityTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string UnitSecondTxt {
            get {
                return ResourceManager.GetString("UnitSecondTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed v m/s.
        /// </summary>
        internal static string UnitSpeedTxt {
            get {
                return ResourceManager.GetString("UnitSpeedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature T degree centigrade.
        /// </summary>
        internal static string UnitTemperatureTxt {
            get {
                return ResourceManager.GetString("UnitTemperatureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal power J/60*60s.
        /// </summary>
        internal static string UnitThermalPowerTxt {
            get {
                return ResourceManager.GetString("UnitThermalPowerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V260*60s.
        /// </summary>
        internal static string UnitV260Txt {
            get {
                return ResourceManager.GetString("UnitV260Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        internal static string UnitVoltageTxt {
            get {
                return ResourceManager.GetString("UnitVoltageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume V m3.
        /// </summary>
        internal static string UnitVolumeCubicMeterTxt {
            get {
                return ResourceManager.GetString("UnitVolumeCubicMeterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume flux m3/24*60*60s.
        /// </summary>
        internal static string UnitVolumeFluxDayTxt {
            get {
                return ResourceManager.GetString("UnitVolumeFluxDayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume flux m3/60*60s.
        /// </summary>
        internal static string UnitVolumeFluxHourTxt {
            get {
                return ResourceManager.GetString("UnitVolumeFluxHourTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume 10-3 m3.
        /// </summary>
        internal static string UnitVolumeLiterTxt {
            get {
                return ResourceManager.GetString("UnitVolumeLiterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string UnitWeekTxt {
            get {
                return ResourceManager.GetString("UnitWeekTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string UnitYearTxt {
            get {
                return ResourceManager.GetString("UnitYearTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownErrorTxt {
            get {
                return ResourceManager.GetString("UnknownErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unmatched type..
        /// </summary>
        internal static string UnmatchedTypeTxt {
            get {
                return ResourceManager.GetString("UnmatchedTypeTxt", resourceCulture);
            }
        }
    }
}
